"""add image name column to exercises table

Revision ID: 133a9edab696
Revises: 17dee17cfdd9
Create Date: 2023-01-30 12:24:40.022900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133a9edab696'
down_revision = '17dee17cfdd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('image_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'image_name')
    # ### end Alembic commands ###
