"""rename completed exercises to completed exercise info

Revision ID: 1443bc83fd9e
Revises: be1e14c74e4c
Create Date: 2023-02-02 15:15:33.700882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1443bc83fd9e'
down_revision = 'be1e14c74e4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('completed_exercise_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.drop_column('users', 'completed_exercises')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('completed_exercises', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('users', 'completed_exercise_info')
    # ### end Alembic commands ###
