"""add foreign key to owner id on journal entry table

Revision ID: 2ea7a1b8f0ac
Revises: adcb62504338
Create Date: 2023-01-29 18:39:40.150912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea7a1b8f0ac'
down_revision = 'adcb62504338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'journalEntries', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journalEntries', type_='foreignkey')
    # ### end Alembic commands ###
