"""add owner id column to journal entries table

Revision ID: 346edf6dd42c
Revises: 9ff6b3ee98d0
Create Date: 2023-01-28 18:31:07.299224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346edf6dd42c'
down_revision = '9ff6b3ee98d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journalEntries', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journalEntries', 'owner_id')
    # ### end Alembic commands ###
