"""remove prompt element table

Revision ID: adcb62504338
Revises: b990c9df2b08
Create Date: 2023-01-29 18:11:52.366818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcb62504338'
down_revision = 'b990c9df2b08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promptElements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promptElements',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"promptElements_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='promptElements_pkey')
    )
    # ### end Alembic commands ###
