"""add completed exercises column to user table

Revision ID: be1e14c74e4c
Revises: 133a9edab696
Create Date: 2023-01-31 18:48:58.957023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be1e14c74e4c'
down_revision = '133a9edab696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('completed_exercises', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'completed_exercises')
    # ### end Alembic commands ###
