"""removed journal entries table

Revision ID: cb76836f4e47
Revises: 1443bc83fd9e
Create Date: 2023-02-07 11:17:25.950837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb76836f4e47'
down_revision = '1443bc83fd9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journalEntries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journalEntries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"journalEntries_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('elements', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='journalEntries_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='journalEntries_pkey')
    )
    # ### end Alembic commands ###
