"""make journal entries an array of JSONB

Revision ID: ff657b2be26a
Revises: 01e190b17189
Create Date: 2023-02-07 11:57:36.086598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff657b2be26a'
down_revision = '01e190b17189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
